### ISSUE TITLE
Setup process running out of memory and spawning too many processes

### ISSUE THREAD

**Issue by VGalata** [PedroMTQ/mantis#34]
Mantis seems to spawn more processes than available cores and to run out of memory during the setup step.
I ran it with 5 cores and 20 Gb, and during the metadata extraction with 5 works the job spawned even more sub-processes and crashed. The error message from the `slurm` job was "out of memory".

I will try to run the job with 12 cores and 48 Gb to see whether the memory issue will appear again.

Used version: 14f75ac

CMD:
```bash
python submodules/mantis/ setup_databases --mantis_config mantis/mantis.config
```

Config:
```
nog_dmnd_ref_folder=/work/projects/ecosystem_biology/data/mantis_references/NOG/
pfam_ref_folder=/work/projects/ecosystem_biology/data/mantis_references/pfam/
kofam_ref_folder=/work/projects/ecosystem_biology/data/mantis_references/kofam/
ncbi_ref_folder=/work/projects/ecosystem_biology/data/mantis_references/NCBI/
tcdb_ref_folder=/work/projects/ecosystem_biology/data/mantis_references/tcdb/
ncbi_weight=0.9
nog_weight=0.8
pfam_weight=0.9
uniprot_ec_weight=0.9
```

Conda YAML:
```yaml
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cython=0.29.21
  - hmmer=3.3.1
  - nltk=3.5
  - numpy=1.19.1
  - psutil=5.7.2
  - python=3.8.5
  - requests=2.24.0
  - sqlite=3.33.0
```

[Log file](https://github.com/PedroMTQ/mantis/files/7669545/mantis_setup_20211207_errors.log)

Screenshots:
![Screenshot from 2021-12-07 16-10-12](https://user-images.githubusercontent.com/5700085/145059811-bb46468c-c0b5-4b16-8362-820e5ede74cd.png)
![Screenshot from 2021-12-07 16-14-37](https://user-images.githubusercontent.com/5700085/145059818-2c68367b-d3ef-48ef-ae93-4471e1183012.png)
